### ISSUE TITLE
Add support for entryComponents

### ISSUE THREAD

**Issue by krokofant** [testing-library/angular-testing-library#100]
I've seen the earlier issues about entryComponents #94 #66  but not being able to put these in presents a real issue when testing via Jest.

Judging from the earlier issues it seemed impossible to support with jest-angular but there is a workaround listed here https://github.com/thymikee/jest-preset-angular/issues/353

So with the TestBed it would look like this:
```typescript
TestBed.configureTestingModule({
	declarations: [MyModalComponent],
	imports: [
		NzModalModule
	],
}).overrideModule(BrowserDynamicTestingModule, {
	set: { entryComponents: [MyModalComponent] },
}).compileComponents();
```

How can we add this to _angular-testing-library_?

It looks like we, more or less, could add it here https://github.com/testing-library/angular-testing-library/blob/89319df8ba8172bb3ff6131534f0cb5b417d1184/projects/testing-library/src/lib/testing-library.ts#L55-L60

**Comment by krokofant** [comment]
@timdeschryver I'm using the Ivy engine. I'm not sure which ngcc magic to apply but I've tried quite a few combinations and it seems very hard to make it work predictably. The workaround for specifying entryComponents work consistently though.

I'm using [nx](https://github.com/nrwl/nx) which by standard executes this postinstall command:
```
ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points
```

To me it seems much easier working around the jest issues by adding the entryComponents where they're needed instead of messing with the ngcc configuration. 😕

**Comment by krokofant** [comment]
Reading a bunch of other issues it does seem like Ivy was not enabled even though ngcc was compiled with those nx default arguments I mentioned.

Just running ngcc with `--properties main` would produce an error also mentioned on the transloco repo. Someone there mentioned, without any specific issue reference to angular/cli, that the newer angular cli compiler packages has some issue. So pinning the angular packages to anything below 9.1.5 would work.

Pinning the angular dependencies to 9.1.4, calling ngcc with `--properties main` and running the tests again it seems like Ivy is used correctly. I'm wondering if these kinds of issues could be minimized somehow if jest-preset-angular (or this testing lib? ¯\\_(ツ)_/¯) could conditionally warn if the tests are not executed in an Ivy context.

**Comment by timdeschryver** [comment]
What about adding a note to the docs?
If that doesn't help, we can revisit and provide this functionality to the library.
