### ISSUE TITLE
Two of the example tests are failing 

### ISSUE THREAD

**Issue by eric-hoose** [testing-library/angular-testing-library#107]
I pulled master from this repo in order to run the tests from the examples to see how they worked, and two of them errored out (the rest of them pass). Not sure if it's a me issue or an actual issue. I'm running Node v12

First failure: `src/app/examples/03-forms.spec.ts`

![image](https://user-images.githubusercontent.com/60657011/84274241-9dda5200-aafd-11ea-9b7a-c3f51960115b.png)

And the second failure is `04-forms-with-material.spec.ts`

![image](https://user-images.githubusercontent.com/60657011/84274332-bea2a780-aafd-11ea-83e2-ac02d447002d.png)

**Comment by eric-hoose** [comment]
Using npm, I tried, `npm i`, `npm run build`, and `npm run test:app` and got the same result

**Comment by timdeschryver** [comment]
I guess this will probably be a version mismatch somewhere. 
I'm not going to look into it as it's currently working fine with the yarn lock file (I hope this will resolve itself with the next major version), feel free to take a look and resolve it with npm.

**Comment by eric-hoose** [comment]
Just in case anyone else stumbles across the issue, it appears that the tests in the example folder only run with yarn, as the yarn-lock probably has the correct dependencies that the package.json is missing somewhere.
