### ISSUE TITLE
@testing-library/user-event dependency looks older than intended

### ISSUE THREAD

**Issue by krokofant** [testing-library/angular-testing-library#117]
I'm looking to use the updated @testing-library/user-event type() command which supports [special characters](https://github.com/testing-library/user-event#special-characters) like `{backspace}`.

I see that [since the 9.3.0 version](https://github.com/testing-library/angular-testing-library/commit/aa5f8911c9102d364dae49a838b2444d245faada#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R33) of angular-testing-library the dependency of user-event should be on version ^11.0.0

Yet, when I upgrade angular-testing-library, user-event is not updated. Checking the dependencies with yarn and npm says that the latest version of `@testing-library/angular` is actually dependent on the older version of `@testing-library/user-event`.

`yarn info @testing-library/angular dependencies`
```
yarn info v1.22.4
{
  '@testing-library/dom': '^7.9.0',
  '@testing-library/user-event': '^8.1.0',
  '@phenomnomnominal/tsquery': '^3.0.0',
  tslint: '^5.16.0'
}
```

`npm info @testing-library/angular dependencies`
```
{
  '@testing-library/dom': '^7.9.0',
  '@testing-library/user-event': '^8.1.0',
  '@phenomnomnominal/tsquery': '^3.0.0',
  tslint: '^5.16.0'
}
```

What happened here? 😕

**Comment by timdeschryver** [comment]
Hi, what you're seeing it the package.json for this repository. The user event is upgraded here, to use it in the examples. 

The actual package.json that is packaged can be found [in the projects](https://github.com/testing-library/angular-testing-library/blob/master/projects/testing-library/package.json#L33). I didn't upgrade user event here. 

The exported userEvent from Angular Testing Library, is in fact a [custom implementation](https://github.com/testing-library/angular-testing-library/tree/master/projects/testing-library/src/lib/user-events) that will be removed in the next major version.

It's now recommended to import `userEvent` directly from user event package.
You can see an example [here](https://github.com/testing-library/angular-testing-library/blob/master/src/app/examples/03-forms.spec.ts#L3).
