### ISSUE TITLE
Make `@testing-library/dom` a peer dependency instead

### ISSUE THREAD

**Issue by NeekSandhu** [testing-library/angular-testing-library#122]
`@testing-library/angular` provides queries straight from `@testing-library/dom` except that it's always a locked version. Meaning that one cannot receive any bug fixes and enhancements related to queries without also updating both `@testing-library/angular` and `@angular/core` itself.

People who are on Angular 8, for example cannot have these critical fixes without upgrading to Angular 9 at the very least (which isn't always an option):
- https://github.com/testing-library/dom-testing-library/pull/580
- https://github.com/testing-library/dom-testing-library/pull/373

Making `@testing-library/dom` a peer dep will give people a lot of wiggle room to what can be achieved as they see fit as opposed to being locked down.

**Comment by timdeschryver** [comment]
I'm hesitant to do this, because consumers will have to install both packages.
You do make a good point tho.

What about the following options:

- What about making Angular a peer dependency
- We could release a new version with the latest DOM package and Angular 8

**Comment by timdeschryver** [comment]
The other packages use a peer dependency to the framework, so I guess we should do that.

**Comment by NeekSandhu** [comment]
> The other packages use a peer dependency to the framework

Unless this package relies on specific angular API's (like `ngZone` for example), which might not be always interoperable across different versions which will force this package to only work with limited versions of angular at a time. Although we can write an adaptor for the API's required by this package which can interoperate calls across versions. This way any version of this library can support any version of angular (within reason of course)

**Comment by NeekSandhu** [comment]
> We could release a new version with the latest DOM package and Angular 8

And this doesn't scale up very well. I mean how far can one stretch things like this.

**Comment by timdeschryver** [comment]
Oh we're already having Angular as a peer dependency 😅.

> And this doesn't scale up very well. I mean how far can one stretch things like this.

Correct, this would only be done for the previous version of Angular and when the change has a big impact.


I think you should be able to run ATL v10 with Angular 9.
Have you tried it?

**Comment by NeekSandhu** [comment]
> Oh we're already having Angular as a peer dependency

... which will force this package to only work with limited versions of angular at a time

> I think you should be able to run ATL v10 with Angular 9

We're on Angular 8 with no immediate plans to upgrade.

**Comment by timdeschryver** [comment]
But have you tried using this package latest version with Angular 8?

**Comment by timdeschryver** [comment]
AFAIK, version 10 of this package should be compatible with earlier versions of Angular.
Is it the recommended way? No, but should work.

**Comment by NeekSandhu** [comment]
No mate it doesn't work:

![image](https://user-images.githubusercontent.com/11316020/88244644-488b7780-cc49-11ea-92ad-6f233833389f.png)


```
TypeError: testing.TestBed.inject is not a function

      at Object.<anonymous> (projects/testing-library/src/lib/testing-library.ts:124:33)
      at step (node_modules/tslib/tslib.es6.js:100:23)
      at Object.next (node_modules/tslib/tslib.es6.js:81:53)
      at fulfilled (node_modules/@testing-library/angular/bundles/testing-library-angular.umd.js:329:32)
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:391:26)
      at ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/proxy.js:129:39)
      at ZoneDelegate.invoke (node_modules/zone.js/dist/zone.js:390:52)
      at Zone.run (node_modules/zone.js/dist/zone.js:150:43)
      at node_modules/zone.js/dist/zone.js:910:34
      at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:423:31)
      at ProxyZoneSpec.onInvokeTask (node_modules/zone.js/dist/proxy.js:160:39)
      at ZoneDelegate.invokeTask (node_modules/zone.js/dist/zone.js:422:60)
      at Zone.runTask (node_modules/zone.js/dist/zone.js:195:47)
      at drainMicroTaskQueue (node_modules/zone.js/dist/zone.js:601:35)
```

**Comment by timdeschryver** [comment]
@NeekSandhu that problem should be resolved in v10.0.1

**Comment by NeekSandhu** [comment]
@timdeschryver works great! however, there are some peer dep warnings that can be addressed because it's now functional with angular 8 as well:

```
warning " > @testing-library/angular@10.0.1" has incorrect peer dependency "@angular/common@^10.0.0".
warning " > @testing-library/angular@10.0.1" has incorrect peer dependency "@angular/platform-browser@^10.0.0".
warning " > @testing-library/angular@10.0.1" has incorrect peer dependency "@angular/animations@^10.0.0".
warning " > @testing-library/angular@10.0.1" has incorrect peer dependency "@angular/router@^10.0.0".
warning " > @testing-library/angular@10.0.1" has incorrect peer dependency "@angular/core@^10.0.0".
```

**Comment by timdeschryver** [comment]
I would like to keep it this way.
It's supported to be used in earlier versions, but it isn't recommended.
