### ISSUE TITLE
Simulating Output events with Testing Library 

### ISSUE THREAD

**Issue by ali-kamalizade-leanix** [testing-library/angular-testing-library#123]
First off, I'm really happy with the Testing Library for Angular: UI tests are now much easier to write!

I have just one question regarding Outputs. I want to simulate an Output of a child component since it's hard to test with Jest & jsdom (infinite scrolling to be exact).

How do I do that with Testing Library?

With Angular testing API I'd do it like this: 
`fixture.debugElement.query(By.css('.someElement').triggerEventHandler('nameOfMyOutput', ...)`

**Comment by miluoshi** [comment]
I'm not sure if I understand your use case correctly, but I don't think you can do this with testing-library alone for nested child component.
You can use `ng-mocks` to mock child component with [MockComponent](https://github.com/ike18t/ng-mocks#mockcomponents) and then emit output event from the mocked element (see example usage in the docs)

**Comment by ali-kamalizade-leanix** [comment]
My use case: the functionality I want to test is hard to test with jsdom so I just want to simulate the Output
I thought Testing Library for Angular might have a wrapper for `triggerEventHandler` but I can also live without it and use the Angular Testing API for these few cases.

**Comment by timdeschryver** [comment]
Have you tried using the `fireEvent.scroll` method?

**Comment by ali-kamalizade-leanix** [comment]
> I'm not a big fan of mocking output events, as @miluoshi mentioned ng-mocks could help but I have no experience with it.
> 
> Have you tried using the `fireEvent.scroll` method?

I did try that function and using `async` (the Angular one, not the native, however I couldn't get it to work with [ngx-infininite-scroll](https://github.com/orizens/ngx-infinite-scroll).

At least before using Testing Library we used mocking of output events heavily. With Testing Library I try to avoid it which works great most of the time! But there are very few cases where I can't test it with the real events either due to jsdom limitations or just because of too complex component structure.
As said above: I'm fine for using the Angular Testing API to mock output events for these few cases as I can see that this is not absolute necessary functionality for Testing Library.

**Comment by timdeschryver** [comment]
I forgot to post it here, but I also tried scrolling at [examples/13-scrolling.component.spec.ts](https://github.com/testing-library/angular-testing-library/blob/master/apps/example-app/app/examples/13-scrolling.component.spec.ts). I could only make it work by setting the `scrollTop` manually...

**Comment by ali-kamalizade-leanix** [comment]
> I forgot to post it here, but I also tried scrolling at [examples/13-scrolling.component.spec.ts](https://github.com/testing-library/angular-testing-library/blob/master/apps/example-app/app/examples/13-scrolling.component.spec.ts). I could only make it work by setting the `scrollTop` manually...

Thanks for the suggestion, I'll try this out as well.
