### ISSUE TITLE
Consider publishing package via angular-testing-library on npm

### ISSUE THREAD

**Issue by MichaelDeBoey** [testing-library/angular-testing-library#13]
Right now the package is published as [`@angular-extensions/testing-library`](https://npm.im/@angular-extensions/testing-library) but it would be clearer and more in line with the rest of the `*-testing-library` family if we can publish it as [`angular-testing-library`](https://npm.im/angular-testing-library) if @brandonroberts would be so kind of transferring the package.

**Comment by timdeschryver** [comment]
See https://github.com/testing-library/dom-testing-library/issues/260 😃
