### ISSUE TITLE
Cannot getByRole for routerLink

### ISSUE THREAD

**Issue by cjhaviland** [testing-library/angular-testing-library#135]
**Background**
I've been trying to do a query by role to check a link on my page using: `screen.getByRole('link', { name: /contact/i })`. This keeps throwing an error as if the the element is undefined.

**Debugging**
Inspecting my element shows it as 
```javascript
<a
  _ngcontent-oet-c21=""
  class="navigation--link navigation--link-active"
  href="/contact"
  ng-reflect-router-link="/contact"
  ng-reflect-router-link-active="navigation--link-active"
  routerlink="/contact"
  routerlinkactive="navigation--link-active"
>
  <i
    _ngcontent-oet-c21=""
    aria-hidden="true"
    class="far fa-clock navigation--icon"
  />
   contact
</a> 
```

I tried debugging while running tests by using `queryAllByRole(component.fixture.nativeElement, 'navigation)` to print out the DOM element and I see this. Looks like when the component is rendered it's not adding in the href like it does for the live site

```javascript
<a
  class="navigation--link"
  routerlink="/contact"
  routerlinkactive="navigation--link-active"
  >
    <i
      class="far fa-clock navigation--icon"
      />
  Contact
</a>
```

I had a similar issue trying to get an image by alt text using `screen.getByRole('img', { name: /company logo/i })` but not sure what was stopping this as Angular isn't adding the alt text.

**Comment by timdeschryver** [comment]
It seems link the `li` is the culprit here.
I use and recommend the testing playground [playground link](https://testing-playground.com/gist/4d27e9acd5ea6c2c6bb43ff8d0c4cbc8/97986d988b937e0dda734379d93801caca8a1f98) to find the correct queries.

**Comment by cjhaviland** [comment]
> It seems link the `li` is the culprit here.
> I use and recommend the testing playground [playground link](https://testing-playground.com/gist/4d27e9acd5ea6c2c6bb43ff8d0c4cbc8/97986d988b937e0dda734379d93801caca8a1f98) to find the correct queries.
> Let me verify that this is behaving as intended, or that it's a bug 😅
> Thanks for creating the issue!

There is no `li` in my HTML structure. The full breakdown is basically:

```html
<nav>
  <a></a>
</nav>
```

There is an `<i>` tag inside of the anchor tag for an icon though.

**Comment by timdeschryver** [comment]
Oh sorry... you're right, I meant `i` tag.

**Comment by timdeschryver** [comment]
@cjhaviland it should work if you close the `i` tag:

```
<a
  _ngcontent-oet-c21=""
  class="navigation--link navigation--link-active"
  href="/contact"
  ng-reflect-router-link="/contact"
  ng-reflect-router-link-active="navigation--link-active"
  routerlink="/contact"
  routerlinkactive="navigation--link-active"
>
  <i
    _ngcontent-oet-c21=""
    aria-hidden="true"
    class="far fa-clock navigation--icon"
  ></i>
   contact
</a> 
```

**Comment by cjhaviland** [comment]
Hey, sorry this is a month later, but I just made some changes to my configuration and tests and it seems I either broke stuff, or just wasn't testing if elements were in the Document in the first place... Pretty much any getByRole() isn't working in my Angular project. I've tried using `component.getRoleBy('...')`, `screen.getRoleBy('...')`, `findRoleBy()` and none of them work, but the debugged html output looks good. If I try it in Testing Playground it works, just not in my project which makes me think it's a configuration issue?

> jest.config.js:
``` javascript
const { pathsToModuleNameMapper } = require('ts-jest/utils')
const { compilerOptions } = require('./tsconfig')

module.exports = {
  preset: 'jest-preset-angular',
  roots: ['<rootDir>/src/'],
  testMatch: ['**/+(*.)+(spec).+(ts)'],
  setupFilesAfterEnv: ['<rootDir>/src/setup-jest.ts'],
  collectCoverage: true,
  coverageReporters: ['html'],
  coverageDirectory: 'coverage/qi-app',
  moduleNameMapper: pathsToModuleNameMapper(compilerOptions.paths || {}, {
    prefix: '<rootDir>/'
  })
}
```

> setup-jest.ts:
``` javascript
import 'jest-preset-angular'
import '@testing-library/jest-dom'
import { configure } from '@testing-library/angular'
import { ReactiveFormsModule } from '@angular/forms'

/**
 * Configure Default Imports
 */
configure({
  defaultImports: [ReactiveFormsModule]
})

/**
 * Mocked Properties of the Global Window object
 */
const mock = () => {
  let storage: { [key: string]: string } = {}
  return {
    getItem: (key: string) => (key in storage ? storage[key] : null),
    setItem: (key: string, value: string) => (storage[key] = value ?? ''),
    removeItem: (key: string) => delete storage[key],
    clear: () => (storage = {})
  }
}

Object.defineProperty(window, 'localStorage', { value: mock() })
Object.defineProperty(window, 'sessionStorage', { value: mock() })

Object.defineProperty(window, 'CSS', { value: null })
Object.defineProperty(window, 'getComputedStyle', {
  value: () => {
    return {
      display: 'none',
      appearance: ['-webkit-appearance']
    }
  }
})

Object.defineProperty(document, 'doctype', {
  value: '<!DOCTYPE html>'
})

Object.defineProperty(document.body.style, 'transform', {
  value: () => {
    return {
      enumerable: true,
      configurable: true
    }
  }
})

/* output shorter and more meaningful Zone error stack traces */
Error.stackTraceLimit = 2

```

**Comment by yuriybelike** [comment]
In case someone comes across this...

This [StackOverflow answer](https://stackoverflow.com/questions/63182537/angular-testing-library-getbyrole-query-works-only-with-hidden-true-option) was what helped me.

The gist is to remove the "getComputedStyle" mock.
(If you are using @angular-builders/jest it's the globalMocks option).
