### ISSUE TITLE
REQUEST: Example of how to component projection with `ng-content`

### ISSUE THREAD

**Issue by knagurski** [testing-library/angular-testing-library#140]
I'm not to using the project, but really love how it has simplified my tests so far. I was hoping to get an example of how to write a test for testing component projection with `ng-content`.

Component I want to test
```js
@Component({
  selector: 'sample-component',
  template: `
    <h1>Hello world</h1>
    <ng-content></ng-content>
  `
})
class SampleComponent {}
```

I would love to see an example of how I can test this with Angular testing library and verify that I can pass another component in and have it projected.

**Comment by portothree** [comment]
There's an example of using `ng-content` here [[component](https://github.com/testing-library/angular-testing-library/blob/master/apps/example-app/app/examples/11-ng-content.ts), [spec](https://github.com/testing-library/angular-testing-library/blob/master/apps/example-app/app/examples/11-ng-content.spec.ts)]

**Comment by timdeschryver** [comment]
Thanks for answering this one @portothree .

@knagurski is this isn't sufficient feel fee to re-open this issue with more information.

**Comment by knagurski** [comment]
Would be great to expand the example with projecting another component instead of just text.

@portothree thanks for pointing each in the right direction 👍
