### ISSUE TITLE
Update @phenomnomnominal/tsquery to 4.1.1 to support TypeScript 4

### ISSUE THREAD

**Issue by krokofant** [testing-library/angular-testing-library#142]
Currently with TypeScript 4 you get this warning:
> warning "@testing-library/angular > @phenomnomnominal/tsquery@3.0.0" has incorrect peer dependency "typescript@^3".

The root package.json has previously been updated to @phenomnomnominal/tsquery 4.1 but the testing-library one was left on 3.0

**Comment by timdeschryver** [comment]
Closed by #143
