### ISSUE TITLE
Component Variables are Undefined

### ISSUE THREAD

**Issue by ReshmiCode** [testing-library/angular-testing-library#155]
On a test for a form, the variables for a component in an expected API call are undefined. In the test I type into the field using fireEvent.change and I know it's working as queryByDisplayValue returns the value entered into the field. But when I run expect(loginSpy).toBeCalledWith it fails as it is called with { email:undefined } instead.
Class addition:
`export class LoginComponent {
  email: string;`
HTML template:
```
<div class="input-cell">
          <label class="fg-text-left" for="test-email">Username or Email</label>
          <input
            [(ngModel)]="email"
            pInputText
            id="test-email"
            type="text"
            autocomplete="off"
          />
</div>
```

**Comment by timdeschryver** [comment]
Hi @ReshmiCode it's unclear to me what the problem is because I don't see all of the code. 
Can you create a reproduction of the issue?

**Comment by ReshmiCode** [comment]
@timdeschryver I've recreated it here: https://github.com/ReshmiCode/Todo-List/pull/1

**Comment by timdeschryver** [comment]
@ReshmiCode for the two way binding to work you should use `input`.

```diff
-  fireEvent.change(screen.getByLabelText(/username or email/i), {
+ fireEvent.input(screen.getByLabelText(/username or email/i), {
      target: { value: "someUser" },
    });
```

I would also like to recommend [`user-event`](https://testing-library.com/docs/ecosystem-user-event) to simulate events:

```ts
    userEvent.type(screen.getByLabelText(/username or email/i), "someUser");
```
