### ISSUE TITLE
Some suggestions for examples

### ISSUE THREAD

**Issue by rafaelss95** [testing-library/angular-testing-library#161]
- Replace `fireEvent.blur(htmlElement)` by `htmlElement.blur()` (https://testing-library.com/docs/guide-events/#focusblur);
- Replace `findBy*`/`getBy*`/`queryBy*` by `screen.*`;
- Add more examples in forms (mainly in material version):
  - Tests using `mat-error` for each  `form-field` instead of a block of errors;
  - Tests with form-friendly components, like `checkbox`, `datepicker`, `chips`, `slider`, `button-toggle`, `autocomplete`.

<hr>

Note that if you like the idea, I can submit a PR ASAP.

**Comment by timdeschryver** [comment]
Thanks for the suggestions, we would love to have these!
Also, TIL for the `blur`. I do think we'll have to test it out for ATL, since this wouldn't trigger a change detection AFAIK.

**Comment by timdeschryver** [comment]
Closing this issue because it's been inactive.
To test forms, you can take a look at [A practical guide to Angular Template-Driven Forms](https://timdeschryver.dev/blog/a-practical-guide-to-angular-template-driven-forms), which has some tests in the examples.
