### ISSUE TITLE
How to work with timers and long asynchronous operations?

### ISSUE THREAD

**Issue by StarpTech** [testing-library/angular-testing-library#170]
Hello, I'd like to ask what is the recommended way to fake timers and move in time in long asynchronous operations. We use `fakeAsync` in combination with `tick` and `flush`.

Working with the testing library feels good but I can't find a word or example about that topic. Do I understand correctly that `angular-testing-library` is a companion to angular testing utils?

**Comment by timdeschryver** [comment]
To be honest, I haven't had this use case, so my experience with it very minimal. 
Do you got a concrete example?
Also, perhaps the [docs](https://testing-library.com/docs/using-fake-timers) could help here.

Angular Testing Library is a Dom Testing Library wrapper around the `TestBed`.

**Comment by StarpTech** [comment]
Imagine the following scenario. A component renders a countdown of X-min. After that, the user is redirected to a different route.

**Comment by timdeschryver** [comment]
Most of my interactions only needed to wait for some milliseconds, so I was alright using the `waitFor` method and `findBy` queries.
Do you have a reproduction, or did you try to suggested approaches from the referenced blog post?

**Comment by StarpTech** [comment]
I can't provide a reproduction but the problem is simple. Sometimes you can't just wait until an element is visible. In that case, we use angular testing utils to flush the macrotask queue. It works! I just wondered if it is common because I couldn't find anything about that in combination with `angular-testing-library`.

**Comment by timdeschryver** [comment]
I added an example in #171, let me know what you think.

**Comment by StarpTech** [comment]
Good example :+1:
