### ISSUE TITLE
Example spec for elements which are added/removed from the DOM on button click (dialog modal window)

### ISSUE THREAD

**Issue by StudioSpindle** [testing-library/angular-testing-library#174]
I'm currently working on a project with a [material dialog component](https://material.angular.io/components/dialog/overview).

What I find challenging is:

**1. Dialog element is not rendered in the container exported from the testing library render method**

Typically you'd use:

```ts
const { container } = render(Component, ...);
```
That container contains all the DOM elements you want to test against. But Angular places an empty div with the class 'cdk-overlay-container' at the bottom of the body tag. When triggering that element so that it opens that div gets the content you'd like to show, and the div itself get's a position fixed with a z-index of 1000.

This means that it does not pop up in the container element returned from the render method. How do you assert against it? For now I'm using `document.querySelector('.cdk-overlay-container')`. Also because it has no role or other attribute to use in a query method of testing library. And is it even correct to use document.querySelector?

**2. Asserting on the DOM updates**

Test cases:
- modal should show when a user clicks on the 'trigger' button.
- modal should return some function when the user clicks on the 'ok' button in the modal
- modal should hide when a user clicks on the 'ok' button in the modal
- modal should hide when the user clicks on the 'cancel' button in the modal
- modal should hide when the user clicks on the backdrop

I'd be interested to see a best in class example for such a component. Perhaps others as well?

**Comment by timdeschryver** [comment]
The best practices has changed over time, we don't encourage using the container of the component anymore.
Testing Library provides `screen`, which has all the functionality of `container`, but has better ergonomics, and it also contains the whole DOM.

The [examples](https://github.com/testing-library/angular-testing-library/tree/master/apps/example-app/app/examples) use `screen`, so you can take a look there for inspiration. 

It would look as follows:

```ts
import { screen, fireEvent, waitForElementToBeRemoved } from '@testing-library/angular'

test('opens and closes the dialog', () => {
  await render(MyComponent)

  fireEvent.click(screen.getByRole('button', { name: /open dialog/i })

  await screen.findByRole('dialog')

  fireEvent.click(screen.getByRole('button', { name: /close dialog/i })
  await waitForElementToBeRemoved(() => screen.getByRole('dialog'));
})
````

**Comment by StudioSpindle** [comment]
Thank you for your reply. So you'd have to query each time?

I.e. this does not work:

```ts
  await render(MyComponent)

  fireEvent.click(screen.getByRole('button', { name: /open dialog/i })

  const modal = await screen.findByRole('dialog');
  expect(modal).toBeTruthy();

  fireEvent.click(screen.getByRole('button', { name: /close dialog/i })
  await waitForElementToBeRemoved(() => modal));
```

but this does:

```ts
  await render(MyComponent)

  fireEvent.click(screen.getByRole('button', { name: /open dialog/i })

  await screen.findByRole('dialog')

  fireEvent.click(screen.getByRole('button', { name: /close dialog/i })
  await waitForElementToBeRemoved(() => screen.getByRole('dialog'));
```

That's interesting.

**Comment by StudioSpindle** [comment]
@timdeschryver So how would you use 'querySelector' method without the container? 

I guess that's just not recommended. It's just that for the material dialog component, I don't think it's possible to target the backdrop element differently without the 'querySelector' method.

**Comment by timdeschryver** [comment]
@StudioSpindle I added an example in #175 it also contains a test with the backdrop.
Can you take a look please?

**Comment by StudioSpindle** [comment]
Great! Interesting approach. 

On line 27 and 47 the render code is duplicated. Especially with imports/declarations this is quite cumbersome if it's a complexer component. 

I've been using a setup() function ([borrowed from mr Dodds](https://kentcdodds.com/blog/avoid-nesting-when-youre-testing#apply-aha-avoid-hasty-abstractions)). 

Is that something you do also?
Or are there some caveats using such a function? I've been experiencing a flakey test where the modal is already opened sometimes but other times isn't.

**Comment by timdeschryver** [comment]
@StudioSpindle we're using `setup` functions on the project that I'm working on.
The tests in this repo don't follow pattern that because I find it easier to read/understand when there are no abstractions.
