### ISSUE TITLE
Wait for app initialization until rendering component

### ISSUE THREAD

**Issue by jbchr** [testing-library/angular-testing-library#176]
**Description**
Angular TestBed is not honoring APP_INITIALIZER contract. This means tests are executed before app initialization is finished. The corresponding Angular issue is this one: https://github.com/angular/angular/issues/24218

In a scenario without testing-library we can easily use a workaround in waiting for the initialization before executing our tests. 

```JavaScript
await TestBed.get(ApplicationInitStatus).donePromise;
```

However when using testing-libraries `render` function we cannot do so, as the lib immediately renders the component after setting up the TestBed

**Proposed solution**
Insert the above line after setting up the TestBed here:
https://github.com/testing-library/angular-testing-library/blob/master/projects/testing-library/src/lib/testing-library.ts#L76

I'm happy to create a small PR for that :)

**Comment by timdeschryver** [comment]
Thanks for opening this issue! I wasn't aware of this behavior.
It would be great if you'd create a PR for this 👍
