### ISSUE TITLE
feat: added override option to RenderOptions to override services

### ISSUE THREAD

**Issue by mabraithwaite** [testing-library/angular-testing-library#18]
Currently it doesn't look like there's a way to override services provided by the component

    @Injectable()
    export class Service1 {
        ...
    }

    @Component({
        providers: [Service1]
    })
    export class Component1 {
        ...
    }

    render(Component1, {
        ...,
        providers: [
            {
                provide: Service1,
                useValue: {}
            } // Doesn't work
        ]
    })

**Comment by timdeschryver** [comment]
The latest version uses Angular version 8, if you can't upgrade you can fix this manually with:

```
TestBed.overrideProvider(Service1, {});
```
