### ISSUE TITLE
The RenderResult interface seems to be missing a few methods

### ISSUE THREAD

**Issue by snowfrogdev** [testing-library/angular-testing-library#182]
The docs for angular-testing-library mention the presence of a `waitFor`, `waitForElementToBeRemoved` and `FireEvent` on the `RenderResult` type but they don't seem to be there.

**Comment by timdeschryver** [comment]
Hi @snowfrogdev , thanks for opening this issue.
It seems like we forgot to update the docs (sorry), from v11 these aren't available on the render result.
You can directly import those methods from `@testing-library/angular` and use them.
