### ISSUE TITLE
ComponentProperties no longer in ngOnChanges

### ISSUE THREAD

**Issue by swhammack** [testing-library/angular-testing-library#188]
After updating to 10.4.0 we saw a bunch of tests that were suddenly failing. After a bit of digging I realized each component implemented `OnChanges` and in the `ngOnChanges()` function we were looking for an `@Input` property to be in the changes object. It seems with the latest changes any `@Input` property that is set in `componentProperties` is never in the changes object in `ngOnChanges`. 

Quick example:

```typescript
@Component
class Component implements OnChanges {
  @Input() someProperty: string

  ngOnChanges(changes: SimpleChanges) {
    if(changes.someProperty) {
      // Do something if @Input property changed
    }
  }
}
```
```typescript
render(Component, {
  componentProperties: {someProperty: 'value'}
})
```

**Comment by timdeschryver** [comment]
Thanks for the report! 
Could you create a reproduction for this behavior, or take a look at how we can fix this in ATL?
I thought we had a test case for this, but it seems like it isn't covering everything 😅

**Comment by swhammack** [comment]
Here is [my fork with a reproduction test.](https://github.com/swhammack/angular-testing-library/blob/bug/onChanges/projects/testing-library/tests/issues/188-onChanges.spec.ts).

**Comment by timdeschryver** [comment]
Thanks a lot @swhammack !

**Comment by swhammack** [comment]
@timdeschryver thanks for the quick fix!
