### ISSUE TITLE
Incompatibility with new testing-library/user-event release

### ISSUE THREAD

**Issue by pcafstockf** [testing-library/angular-testing-library#190]
The tests for my angular app make many calls to [userEvent.type](https://github.com/testing-library/user-event#typeelement-text-options) in testing-library/user-event.

With the new [release of testing-library/user-event](https://github.com/testing-library/user-event/releases/tag/v13.0.0), these tests (which were passing), now break, and the cause *seems* to be that angular is no longer detecting changes triggered by typing.
This is not to surprising given the changes described in this [user-event PR](https://github.com/testing-library/user-event/pull/581).

Indeed, rolling back to the previous version of userEvent results in successful tests again.

I'm happy to do more research/debugging, but need a little guidance...
It's not clear to me how the angular-testing-library has been detecting the changes triggered by the previous userEvent.type implementation.  If I understood that mechanism better, it might help me provide more information about the current incompatibility.

Thoughts?  Suggestions?

**Comment by timdeschryver** [comment]
Hi, thanks for opening this issue.
The change detection is triggered by configuring dom testing library [here](https://github.com/testing-library/angular-testing-library/blob/master/projects/testing-library/src/lib/testing-library.ts#L63-L66).

The new `type` implemention should use this config.

**Comment by pcafstockf** [comment]
That was exactly what I needed.  Thank you!

Closing this issue, as I was able to determine it had nothing to do with any testing-library project.

A 3rd party component (which uses setTimeout heavily), just happened to work because of the way userEvent.type had been implemented.

I was able to use the config mechanism that you pointed out, to write my own wrapper to keep the 3rd party component happy (and even clean up some hacks I had put in my tests to accommodate that component).
:-)

**Comment by timdeschryver** [comment]
Is this something that we would also need to fix in this library?
Or was the fix specific to your codebase?

**Comment by pcafstockf** [comment]
Lol.  That is why I closed, reopened and again closed this issue...  I was trying to decide the same thing.

There may be folks that run into a similar problem, but I feel this is ultimately a user land issue, not something for the angular-testing-library.

The 3rd party component (Syncfusion Angular Grid) receives the events from `type`, but processes them async (sometimes even multiple async calls to process an event).  By the time the component has finished its changes, the angular-testing-library has already called `detectChanges`.  I admit to a little hand waving here as I haven't identified the exact difference's and event sequences between a user actually typing (which works) and `userEvent.type` (which sometimes did not).

My "fix" was to use the `asyncWrapper` to call `setTimeout(r, 0)` *before* angular-testing-library gets a chance to call `detectChanges`.  

**On a related note**, it would be great if angular-testing-library took a tail patch approach to `eventWrapper` instead of overwritting (and ignoring) whatever was previously configured.
