### ISSUE TITLE
Broken tests for the components with setters in Input

### ISSUE THREAD

**Issue by GlebIrovich** [testing-library/angular-testing-library#191]
Hey there! I noticed, that updating to 10.4.1 cause some of my tests failing. I investigated a bit and it seems, that the components, which are using setters in the inputs are not invoking logic that was in the setter before.

I assume it might be caused by this change in 10.2.1 which changes the way how component properties are added to the fixture:
https://github.com/testing-library/angular-testing-library/blob/4b6e491cf7f748f828f66589239651f7f0818f55/projects/testing-library/src/lib/testing-library.ts#L203

I am curios , is it a bug? And if not, what is the preferred way to test components which use `set` in the `@Input`?

**Comment by timdeschryver** [comment]
Oh shoot, it could be a bug. 
It seems like we don't have any tests to cover this behavior, because it should "just" work.

Can you perhaps create PR with a fix, or a test with the expected behavior?

**Comment by GlebIrovich** [comment]
@timdeschryver thanks for clarification! I have no experience contributing to an open source project, but it seems like a sign to give a shot. I will prepare a PR with tests at least.

**Comment by timdeschryver** [comment]
Thank you in advance!
If it takes too long, or if you're having troubles feel free to ask for help, or just to paste the test here 🙂

**Comment by GlebIrovich** [comment]
here is a [PR](https://github.com/testing-library/angular-testing-library/pull/192)

Let me know if I missed anything
