### ISSUE TITLE
Test case for mat-menu.

### ISSUE THREAD

**Issue by pradhanadi** [testing-library/angular-testing-library#195]
So I have a component that uses mat-menu. When I call fireEvent.click(), I get an error: TestingLibraryElementError: Unable to find role="menu" in console. 

```
test('it should open pages menu on button click', async () => {
  
  let component = await render(PaginationComponent, {
    imports:[MaterialModule]
  });
  let buttonCLick = fireEvent.click(screen.getByTestId('openChangePageSizeMenu'));
  expect(buttonCLick).toBeTruthy();

  await screen.findByRole('menu');

});
```
This is the code that I wrote. Can someone help me out? I am fairly new in Testing. 

Thanks.

**Comment by timdeschryver** [comment]
Can you create a runnable reproduction @pradhanadi ? Either in this repository, or somewhere else.

**Comment by pradhanadi** [comment]
> Can you create a runnable reproduction @pradhanadi ? Either in this repository, or somewhere else.

Hi @timdeschryver, I have created a repo.

**Comment by timdeschryver** [comment]
This is because the menu is hidden to testing library, as a fix you can do the following.

```ts
screen.getByRole('menu', { hidden: true });
```

**Comment by pradhanadi** [comment]
Will this work for mat dialog as well? Getting same error for mat-dialog

**Comment by pradhanadi** [comment]
> This is because the menu is hidden to testing library, as a fix you can do the following.
> 
> ```ts
> screen.getByRole('menu', { hidden: true });
> ```

This worked!. Thanks @timdeschryver :)

**Comment by timdeschryver** [comment]
Yes, it will work.
You can also configure TL to have `hidden true` as default, so you don't have to repeat it in tests.

I think this is due to the overlay of material, but i'll have to investigate it more to be sure.

```ts
configure({
  dom: {
    defaultHidden: true,
  },
});
```

**Comment by pradhanadi** [comment]
Can you also help me out with service test case for mat dialog? I'll share the code.

**Comment by pradhanadi** [comment]
> Yes, it will work.
> You can also configure TL to have `hidden true` as default, so you don't have to repeat it in tests.
> 
> I think this is due to the overlay of material, but i'll have to investigate it more to be sure.
> 
> ```ts
> configure({
>   dom: {
>     defaultHidden: true,
>   },
> });
> ```

Yes it worked with mat-dialog as well. Can't believe  `{hidden:true}` was the solution my team and me were not able to find.

**Comment by pradhanadi** [comment]
@timdeschryver: A strange thing is happening. So I added `hidden: true` to all my mat-menu and mat-dialog test cases, they were successful at first, but now they are failing. Any idea?
