### ISSUE TITLE
How to write test case for mat-dialog service?

### ISSUE THREAD

**Issue by pradhanadi** [testing-library/angular-testing-library#196]
I have a dialog component and it has a service. The service has a function for opening the dialog. The service file looks like this:
```
export class DialogService {
  constructor(private dialog: MatDialog) {}

  openDialog(heading, bodyContent, buttonText) {
    let dialogRef = this.dialog.open(DialogComponent, {
      data: {
        heading: heading,
        bodyContent: bodyContent,
        buttonText: buttonText
      },
    });
  }
}
```

I need to write a test case for this service. So far I have this in my service.spec.ts:

```
import { DialogService } from './dialog.service';

describe('DialogService', () => {

  let service: DialogService;

  beforeEach(() => {
    service = new DialogService();
  })

  test('should be created', (done) => {
    expect(service).toBeTruthy();
  });
});
```

But I get an error:

Expected 1 arguments, but got 0.ts(2554)
dialog.service.ts(10, 15): An argument for 'dialog' was not provided.

Can anyone help me please?

**Comment by timdeschryver** [comment]
I don't think this has anything to do with ATL?
`DialogService` expects a `MatDialog` as input, but it's not provided with `new DialogService()`.
