### ISSUE TITLE
Printing lots of ReferenceError messages at the end of Jest test execution

### ISSUE THREAD

**Issue by pradhanadi** [testing-library/angular-testing-library#197]
While running the test case for a component, I get an error: `ReferenceError: You are trying to access a property or method of the Jest environment after it has been torn down.`  but the same test case is working absolutely fine for other component.

Relevant code:
my component.ts
```
isLoading: boolean = true;

ngOnInit(): void {
    setTimeout(() => {this.isLoading = false;}, 1000);
   
  }
```

my component.spec.ts
```
jest.useFakeTimers();
import { render, screen, waitFor } from '@testing-library/angular';
import { createMock } from '@testing-library/angular/jest-utils';
import '@testing-library/jest-dom';

let component: DevicesComponent;

render(DevicesComponent, {
  imports: [],
  declarations:[SkeletonLoaderComponent, PaginationComponent],
  schemas: [NO_ERRORS_SCHEMA]
});

test('it should set isLoading variable to false after 1000 ms', async () => {
  component.isLoading = true;
  jest.setTimeout(1000);
  component.isLoading = false;
});
```

my component.html:

```
<div *ngIf="isLoading; else elseBlock">
	<app-skeleton-loader></app-skeleton-loader>
</div>

<ng-template #elseBlock>
<!-- Rest of the code -->
</ng-template>
```

What amuses me is, I have same set of code for another component and it works fine there.

**Comment by timdeschryver** [comment]
This is hard to debug without a reproduction.
Would it be possible to create one? 
Also, am I correct to assume that the same test doesn't log messages with a jasmine/karma setup?

**Comment by timdeschryver** [comment]
Feel free to reopen this issue with a reprodution.
