### ISSUE TITLE
Add ESLint with the eslint-plugin-testing-library and adjust examples

### ISSUE THREAD

**Issue by the-ult** [testing-library/angular-testing-library#198]
## Context
To provide the 'best' examples possible it would be good to use the [eslint-plugin-testing-library](https://github.com/testing-library/eslint-plugin-testing-library) and [eslint-plugin-jest-dom](https://github.com/testing-library/eslint-plugin-jest-dom)

And update the examples with the best practices.

@see [common-mistakes-with-testing-library](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#not-using-testing-library-eslint-plugins)

**Comment by timdeschryver** [comment]
Thanks @the-ult , I was waiting on a migration schematic and NX recently released one.
If you want, feel free to migrate the linter.

**Comment by the-ult** [comment]
Hi @timdeschryver ,

I will try to find some time this week to add a PR.
Would you prefer 2 different PR's or can I combine them?
- replace TSLint with ESLint
- add testing-library eslint rules

**Comment by timdeschryver** [comment]
@the-ult yea, I think that would be ideal!

**Comment by the-ult** [comment]
Hey @timdeschryver I added the pull-request for the migration part
Could take look. And check/test it where needed?
