### ISSUE TITLE
test authentification

### ISSUE THREAD

**Issue by Chr111** [testing-library/angular-testing-library#210]
Hello, 
I'm looking for a way for testing my component. Could you help me please?
thank
Chris

import {HttpClient} from "@angular/common/http";
import {Injectable} from '@angular/core';
import {Router} from '@angular/router';

@Injectable()
export class AuthService {
  URL = "https://prod.api.sofavod.com/";
  isAuth = false;
  username: string;
  token: string;
  currentUser;

  constructor(private httpClient: HttpClient, private Router: Router) {
  }

  signIn(login: string, password: string) {
    const ident =
      {
        username: login,
        password: password
      };

    let json = JSON.stringify(ident);
    const headers = {
      'Content-Type': "application/json",
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'POST',
      'Access-Control-Allow-Headers': 'Content-Type'
    }
    let promise = this.httpClient.post<any>('https://prod.api.sofavod.com/auth/signin', json, {headers}).toPromise().then(
      (response) => {
        console.log(response)
        this.currentUser = JSON.parse(localStorage.getItem('currentUser'));
        localStorage.setItem('token', response.accessToken);
        localStorage.setItem('idUser', response.id)
        this.isAuth = true;
        return response;
      },
      (error) => {
        this.isAuth = false;
      })
    return promise;
  }

  signOut() {
    this.isAuth = false;
    localStorage.clear();
    this.Router.navigate(['auth']);
  }

}

**Comment by timdeschryver** [comment]
Hi, I'm trying to keep the issues strictly for issues.
If you need help, feel free to join our [discord server](https://discord.gg/testing-library).
