### ISSUE TITLE
`render(template)` syntax highlighting on IDE like vscode

### ISSUE THREAD

**Issue by lacolaco** [testing-library/angular-testing-library#227]
Angular's inline template HTML is treated as an HTML part by VSCode because Angular's extension registers that. Of course, the template string you pass to `render(template)` is not treated as HTML, and you will not get assistance with closing tag completion, code formatting, or syntax highlighting.

I know it's not easy, but I think testing-library will be very convenient if this can be achieved.

![image](https://user-images.githubusercontent.com/1529180/121765001-f023d800-cb82-11eb-8c22-b31cecb53892.png)

**Comment by timdeschryver** [comment]
🤔 I think this should be doable,  let's give this a shot.
