### ISSUE TITLE
[Regression] ESLint plugin plugin:testing-library/angular & plugin:jest-dom/recommended are removed

### ISSUE THREAD

**Issue by the-ult** [testing-library/angular-testing-library#235]
@timdeschryver It seems like you (accidentally?) removed
```
"extends": ["plugin:testing-library/angular", "plugin:jest-dom/recommended"]
```
with the upgrade to/for Angular 12

[See Commit](https://github.com/testing-library/angular-testing-library/commit/e6d2e84470abdb6ff8c61a2494cc0fed2805ef72#diff-45673f3f4db2127124203aa2c44baf45de285dc6e30c793f368fd1829225a630)

both in `apps/example-app` and `apps/example-app-karma`

**Comment by timdeschryver** [comment]
Yikes, I think this accidently got removed with a schematic. Good catch! Feel free to open a PR to reintroduce the linter.

**Comment by timdeschryver** [comment]
Yea there's no rush @the-ult .
If you can't make it today another time is also great, or I can also add it 🙂

**Comment by the-ult** [comment]
OK.. got a PR ready 👍
