### ISSUE TITLE
fixture.destroy() not called in cleanup

### ISSUE THREAD

**Issue by Lukas-Kullmann** [testing-library/angular-testing-library#240]
Hey there, I ran into an issue that I could fix by calling `fixture.destroy()` at the end of my test. The details are not really important here.

Apparently, the cleanup function in projects/testing-library/src/lib/testing-library.ts only removes the elements from the dom. It does not destroy the fixture.

Is there a reason for that? I think destroying the fixture at the end of each test is a good idea since it also destroys the components which might free quite some memory in most cases. And I can also not think of any use case where you would not want to destroy the fixture at the end of a test.

**Comment by timdeschryver** [comment]
I think this is a good idea! 
If you want, you can create a Pull Request.
