### ISSUE TITLE
Upgrade deps

### ISSUE THREAD

**Issue by timdeschryver** [testing-library/angular-testing-library#258]
With the release of Angular we should also upgrade the deps in this lib:

- Angular
- NX
- ???

This could also lead to a breaking change, and we can merge #257 with the release.

If someone wants to pick this up, feel free to add a comment.

**Comment by the-ult** [comment]
As soon as NX releases the migration for Angular 13, I can create a PR.
So, probably next week

**Comment by the-ult** [comment]
It is probably a good idea to see if Angular Testing Module teardown is properly handled atm.
And perhaps we can make it configurable or something. An extra option for `Render`?

see: https://dev.to/this-is-angular/improving-angular-tests-by-enabling-angular-testing-module-teardown-38kh

**Comment by timdeschryver** [comment]
@the-ult  +1 for adding the config option!
It should be handled correctly (#253), but it can't harm to double check.

**Comment by the-ult** [comment]
Gonna try and create a PR this week
