### ISSUE TITLE
Exclude componentDeclarations from TestingModule

### ISSUE THREAD

**Issue by szabototo89** [testing-library/angular-testing-library#27]
For the sake of simplicity, there was a change in the `render` usage and we don't need to specify the tested component in the `declarations` within the RenderOptions object. However most of the time the component is declared in a NgModule, because of many dependencies and it also make tests more resilience. 

With the current mechanism we're getting these errors:

`Error: Type XYZComponent is part of the declarations of 2 modules: XYZModule and DynamicTestModule! Please consider moving XYZComponent to a higher module that imports XYZModule and DynamicTestModule. You can also create a new NgModule that exports and includes XYZComponent then import that NgModule in XYZModule and DynamicTestModule.`

I could cherry-pick every dependency of the component and specify it, but it would make the tests more brittle. If it's possible I would like to avoid it. 

Related code: https://github.com/testing-library/angular-testing-library/blob/master/projects/testing-library/src/lib/testing-library.ts#L38

Could you provide a configuration option to exclude componentDeclarations from TestingModule?

**Comment by timdeschryver** [comment]
I haven't thought about this while making the change. Thanks for opening this issue!
I think we can make it smart enough to exclude it, so you as a dev shouldn't think about it.

**Comment by timdeschryver** [comment]
Misread the issue, this can't be done automatically AFAIK.
See #28 for the fix, will probably get released in soon.

**Comment by szabototo89** [comment]
Yeah, this is exactly what I was thinking of! Thanks!
