### ISSUE TITLE
... has incorrect peer dependency "@angular/forms@13.0.2"

### ISSUE THREAD

**Issue by Quraian** [testing-library/angular-testing-library#270]
Hi, there seems to be some odd (correct me if I'm wrong) peer dependencies:

<pre>
warning " > @testing-library/angular@11.0.0" has incorrect peer dependency "@angular/forms@13.0.2".
warning " > @testing-library/angular@11.0.0" has unmet peer dependency "@testing-library/user-event@^13.5.0".
</pre>

**Comment by timdeschryver** [comment]
@Quraian Version 11 of Angular Testing Library is recommended to be used with Angular 13.

**Comment by Quraian** [comment]
I am using version 13, I just tried win a new Angular 13 project but still see this warning.
If this is not appearing with you then you can close it, cause I'm not sure about it.

**Comment by timdeschryver** [comment]
Thanks @Quraian , I was able to reproduce it.
This should be resolved in v11.0.2
