### ISSUE TITLE
Fix render() function return type

### ISSUE THREAD

**Issue by szabototo89** [testing-library/angular-testing-library#29]
https://github.com/testing-library/angular-testing-library/blob/master/projects/testing-library/src/lib/testing-library.ts#L16

There is no explicit type for render function declaration and typescript generates this declaration type file: 

```ts
// testing-library.d.ts
import { Type } from '@angular/core';
import { RenderOptions } from './models';
export declare function render<T>(template: string, renderOptions: RenderOptions<T>): any;
export declare function render<T>(component: Type<T>, renderOptions?: RenderOptions<T>): any;
```

Could you specify their return types with `RenderResult`?

**Comment by timdeschryver** [comment]
Thanks for addressing this, this is indeed wrong and the return type should be `Promise<RenderResult>`.

Do you want to create a Pull Request with a fix?

**Comment by szabototo89** [comment]
Sure, I'll fix it.
