### ISSUE TITLE
Angular Ag-Grid row group empty render when querying DOM elements with angular-testing-library

### ISSUE THREAD

**Issue by urbullet** [testing-library/angular-testing-library#293]
[As mentioned in StackOverflow](https://stackoverflow.com/questions/72144303/angular-ag-grid-row-group-empty-render-when-querying-dom-elements-with-angular-t), I have an ag-grid that contains different columns and column groups, as well as row groups.

I am trying to test the DOM elements displayed in the row group using Jest and Angular Testing Library. The problem I am having is that the DOM renderer for the test does not detect any children of that row and only shows it as a self-enclosed DIV tag with no childer. But when I check it on the web browser I can see all the group rows and the nested rows within them.

I initially thought it was due to the row virtualization, but I have set the `rowBuffer` to 99999 and the cell fails to render anything but an empty DIV still.

What could be the issue? all the other cells and columns are rendering correctly, but the cell that contains a row group fails to render anything.

![image](https://user-images.githubusercontent.com/7741940/167633672-7c45c705-8d36-4284-ba6f-212ebc6bd70d.png)

The image above shows what that row group is being rendered like through angular-testing-library. While in the browser that DIV contains multiple child SPANs and other elements.

**Comment by timdeschryver** [comment]
I'm sorry but I don't have experience with ag-grid.
If you provide an example, I could take a look.
Maybe the following blog could also be of help: https://blog.ag-grid.com/using-react-testing-library-with-ag-grid/

**Comment by urbullet** [comment]
ag-grid provides many powerful features, including the [row grouping](https://ag-grid.com/javascript-data-grid/grouping/#example-default-row-grouping). It is basically combining rows based on grouping columns that are defined like in the example. 

The problem is that when I go to the page containing the grid, I am able to view those groupings rows and their child rows as well. But when I do a screen.debug I cannot find any child or anything else but that enclosed DIV I shared in the question with no children nested from it (children are the nested groups).

**Comment by timdeschryver** [comment]
@urbullet Yea, but what I meant was an executable example where the test is failing.

**Comment by timdeschryver** [comment]
One more question on my end, does this test work by using the Angular TestBed, without Angular Testing Library?

**Comment by urbullet** [comment]
It works with TestBed yes. It also passes on Cucumber.JS tests.

Further updates on another case where else I am facing this issue: 

I have a 3rd party component that I am using inside my modal. I am querying the screen where the modal is open and all the form elements inside of it are showing, including my 3rd party component. Now there is an issue that the HTML elements of that 3rd party component are rendered but to a certain level. And the elements after that level are shown as an empty div as well (just like the grid issue). 

So, it is not just an ag-grid issue, but more of an n-level child rendering issue.

I have tried rendering the nth child of that component separately and it does actually render what I was looking for. Is there an option I am missing to force the render of deeply nested components?

**Comment by timdeschryver** [comment]
This seems to be a problem with Jest, more specifically js-dom.
To render the items ag-grid is doing something with screen size, height of rows, available size,... which isn't supported with js-dom (AFAIK).

What I tested:

- ran the same test with Karma, and the test succeeded
- ran the same test in Jest but without using Angular Testing Library, the test still fails

With these observations I think this isn't Angular Testing Library specific.
