### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by jadengis** [testing-library/angular-testing-library#296]
### Description

Currently standalone components, directives and pipes cannot be tested because they are automatically added to the `declarations` portion when configuring TestBed internally. Angular throws an error when trying to declare a standalone component. 

### Proposed solution

Add the component/directive/pipe-under-test to the imports section of `TestBed.configureTestingModule` if the component is standalone.

### Alternatives considered

There isn't really a way to work around this.

**Comment by rothsandro** [comment]
I did not test it but maybe it helps to set `excludeComponentDeclaration: true`.

**Comment by timdeschryver** [comment]
Hi, sadly I didn't have the bandwidth to proactively test ATL with standalone components.
I do think that  `excludeComponentDeclaration` should work.
Maybe we can improve the API for standalone components later.

**Comment by jadengis** [comment]
Do you accept PRs? There is an `isStandalone` function that can be used to put the component in imports instead of declarations when it's a standalone component.

**Comment by jadengis** [comment]
I opened a PR which upgrades to v14 and fixes the `render` api to add standalone components to `imports` instead of `declarations`. With this change `await render(StandaloneComponent)` works. Let me know what you think. :pray:

**Comment by timdeschryver** [comment]
Great, thanks @jadengis (of course PRs are more than welcome, thanks for that!).
I left a comment in the PR.
