### ISSUE TITLE
WARN: 'Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?'

### ISSUE THREAD

**Issue by jadir-junior** [testing-library/angular-testing-library#313]
After update to Angular 14.1.2 the components with inject Router begin to show the WARN below in tests

WARN: 'Navigation triggered outside Angular zone, did you forget to call 'ngZone.run()'?'

how can I disabled these warns?

**Comment by timdeschryver** [comment]
Thanks for raising this issue @jadir-junior .
It seems like you're right, I'll have a closer look at this at the start of next week.
