### ISSUE TITLE
how test a component with appentTo "body"

### ISSUE THREAD

**Issue by jadir-junior** [testing-library/angular-testing-library#317]
Hi I have a component modal with a prop to appent to body where use document.body.

How do I render the body on test to test my modal is open in the body?

I see that react testing library have some like this
https://testing-library.com/docs/react-testing-library/api/#container

but in angular testing library I don't see that

**Comment by timdeschryver** [comment]
I'm not sure what you mean @jadir-junior 
(Angular) testing library has `screen`, with it you got access to the whole document body.

You could use `screen.getByRole` if you want to query the modal in the document.
