### ISSUE TITLE
TestingLibraryElementError: Unable to find an accessible element with the role "button"

### ISSUE THREAD

**Issue by jzaburunov** [testing-library/angular-testing-library#320]
Hello fellas. I encountered this issue : `TestingLibraryElementError: Unable to find an accessible element with the role "button"` while trying to take an element by advice of testing playgound app: 

<img width="358" alt="Screenshot 2022-11-09 at 21 54 09" src="https://user-images.githubusercontent.com/11402322/200916670-9e76a0b4-8155-4820-898e-155aa22ff44d.png">

And looks like in browser , this works, `screen.getByRole('button')` returns expected result. 

When I print out a debug DOM, there are no role attribute in element's tag, whereas in browser all attributes are in place (see code below). It looks like the component is not recognised by angular and other lifecycle things doesn't appear, like attribute `_ngcontent-vyg-c1` , which is in the browser. 

```
// debug output:
  <component
              ng-reflect-unwrap=""
              ng-reflect-variant="no-border"
              unwrap=""
              variant="no-border"
            >
```

Please help to understand what I missed.

**Comment by jzaburunov** [comment]
This is because JSDOM doesn't work with native web components.

**Comment by timdeschryver** [comment]
Thanks for the update @jzaburunov
