### ISSUE TITLE
Reduce peer dependencies for easier integration

### ISSUE THREAD

**Issue by shaman-apprentice** [testing-library/angular-testing-library#333]
As a developer I want an easy integration into my project.

I am currently working on a project, which has some legacy dependencies which require `rxjs@6` as peer dependency and their update would be quite some work.

This (awesome :) ) testing-library has `rxjs@7` as peer dependency [declared here](https://github.com/testing-library/angular-testing-library/blob/main/projects/testing-library/package.json#L36).  

This makes the dependency tree of the project invalid when integrating this testing library. I know that I can install nevertheless with `--legacy-peer-deps` but this looks like an awful error source to me.

Would it be feasible for you to integrate `rxjs@7` as dev dependency? I see no hard downside in it? If you could also release it within `@testing-library/angular@11` for Angular 13 support, that would be awesome for me.

**Comment by timdeschryver** [comment]
That seems reasonable.
Do you want to create a PR for this (v15 is planned to have the following rxjs dependencies `"^6.5.3 || ^7.4.0"`)?

When that's done, I'll also take a look how to release a new version for `@testing-library/angular@11` because I think I'll have to do that manually.
