### ISSUE TITLE
Where is jest-utils?

### ISSUE THREAD

**Issue by dgsmith2** [testing-library/angular-testing-library#34]
I'm looking to update a project from angular-testing-library to @testing-library/angular.  However, jest-utils isn't packaged.  Therefore `createMock` and `provideMock` are unavailable.  It this intentional?

**Comment by timdeschryver** [comment]
Seems like there went something wrong, with the commit.
I will release a new version ASAP.

**Comment by dgsmith2** [comment]
Just to make sure you don't end with a regression, I did see that it was separated out in #15.  I am simply looking for the means to optionally pull it in.  Thanks!

**Comment by timdeschryver** [comment]
Thanks @dgsmith2 🙂
