### ISSUE TITLE
[Bug?] TypeError: (0 , import_core.isStandalone) is not a function after upgrading to Angular 15.1

### ISSUE THREAD

**Issue by mnkyjs** [testing-library/angular-testing-library#356]
I think the change from #353 was not quite enough and the problem with Angular 15.1 still persists. I was able to continue to recreate this problem.

**Comment by mnkyjs** [comment]
@timdeschryver the latest version 13.1.0

**Comment by TrustNoOneElse** [comment]
@mnkyjs It sounds more like that you are not on Angular version 15.1, core.IsStandalone is existing in the core package of Angular 15.1. For Angular 15 you need to stay on testing libary version 13.0.2. If you go back to that testing libary version you should no longer have this error or when you upgrade to 15.1. In our project its all working perfectly with many test suites.

**Comment by mnkyjs** [comment]
Oh 🤦 you are absolutely right! I relied on the renovate bot here and didn't realize that on my branch where I update to Angular 15.1, it wasn't the current version 13.1.0.... 

Thank you very much for your feedback! Everything is working now!
