### ISSUE TITLE
[Question] Test NGXS @State with Angular Testing Library

### ISSUE THREAD

**Issue by vmuresanu** [testing-library/angular-testing-library#357]
Hello, recently we migrated our test to Angular Testing Library with Jest and so far it is awesome.

In your examples I saw tests with Ngrx and both examples are using a Component that injects Store in it, and this is how you test it. 
In our case we are using NGXS state management and following Facade pattern, therefore in components we are injecting a facade (that is a regular service). It has the role of dispatching actions and selecting from the state.
Since we are injecting facade in components we are mocking it just like any other injected services. And then we unit test `@State` separately. Is there any good way of testing State with Angular testing library, or should we not mock the facade in component testing?

Currently we are testing components with testing library, and `@State` with TestBed.

If we go with the approach to not mock the facades, then we have kind of integration testing and all the flows will be handled in component specs - which is a debatable approach. We would like to separate Component testing with State testing. 

For example using TestBed this is how we configure state tests: 

```ts
  beforeEach(async () => {
    TestBed.configureTestingModule({
      imports: [NgxsModule.forRoot([SomeState])],
      providers: [
        {
          provide: SomeApiService,
          useValue: createMock(SomeApiService),
        }
      ],
    });

    store = TestBed.inject(Store);
    apiService = TestBed.inject(SomeApiService);
  });
```
 Is it possible to somehow do the same approach with Testing Library? Thanks in Advance

**Comment by timdeschryver** [comment]
Hi, we're glad you're liking it!

Angular Testing Library is specifically to render components and interact with them, we don't have anything (yet?) to test plain services.

I prefer to write integration tests as you mentioned (or recently, skip this test and write a cypress/playwright test for this case). 
For complex services, I usually create services manually instead of relying on the TestBed for this.

**Comment by timdeschryver** [comment]
I don't know if NGXS has something for this, NgRx has a couple of helper utilities to work around the TestBed.

https://ngrx.io/guide/store/testing#testing-without-testbed

**Comment by vmuresanu** [comment]
Thanks a lot for you replies!
