### ISSUE TITLE
rerender does recreate the component breaking ngOnChanges

### ISSUE THREAD

**Issue by shaman-apprentice** [testing-library/angular-testing-library#360]
# Bug

First of all of course thx for all the great open source work done! :)

## Expected behavior

GIVEN a component which  depends on previous value within `ngOnChanges`
WHEN calling `rerender` with new input properties
THEN `ngOnChanges` gets called with previous and new current value.

## Actual behavior

The component gets recreated and changes within `ngOnChanges` are always initial changes.

## Minimal reproduction

The second expect in the test below will fail.
```ts
@Component({
  selector: 'atl-fixture-2',
  template: `{{
    hasImproved
      ? 'Great, I cannot remember any result as good as yours! Keep throwing!'
      : 'You can do better than that... Try again!'
  }}`,
})
class MotivatorComponent implements OnChanges {
  @Input() dice = 1;

  hasImproved = false;

  ngOnChanges(changes: SimpleChanges): void {
    console.log(changes.dice);
    if (!changes.dice.firstChange && changes.dice) {
      this.hasImproved = changes.dice.currentValue > changes.dice.previousValue;
    }
  }
}

test('"ngOnChanges" gets called with an update', async () => {
  const { rerender } = await render(MotivatorComponent, {
    componentInputs: { dice: 1 },
  });

  expect(screen.getByText('You can do better than that... Try again!')).toBeInTheDocument();

  await rerender({
    componentInputs: {
      dice: 2,
    },
  });

  expect(screen.getByText('Great, I cannot remember any result as good as yours! Keep throwing!')).toBeInTheDocument();
});
```

The two console logs will be:
```
console.log
    SimpleChange {
      previousValue: undefined,
      currentValue: 1,
      firstChange: true
    }

      at MotivatorComponent.ngOnChanges (tests/rerender.spec.ts:75:13)

  console.log
    SimpleChange {
      previousValue: undefined,
      currentValue: 2,
      firstChange: true
    }
```

The actual console logs in a small demo app are:
```
{previousValue: undefined, currentValue: 1, firstChange: true}
{previousValue: 1, currentValue: 2, firstChange: false}
```

**Comment by shaman-apprentice** [comment]
I was so free to prototype a possible solution in https://github.com/testing-library/angular-testing-library/pull/361. Feedback or just copy pasting it for a possible solution is very welcome :)

**Comment by timdeschryver** [comment]
@shaman-apprentice this is intended, `rerender` destroys the component and creates a new instance.
I think what you're looking for is `change`.

https://testing-library.com/docs/angular-testing-library/api#change

**Comment by shaman-apprentice** [comment]
Thanks a lot for the fast reply and pointing me to the docs :heart: To be honest, I haven't looked at the docs. I just assumed by my React knowledge... :angel: :disappointed: 

In accordance to my React knowledge I find it natural to assume, that rerender does, what `change` does. However I am not sure if it is just me.^^

Although the docs are not clear to me as well:
> Re-render the same component with different props. Input properties that are not defined are cleared. This calls detectChanges after the props are updated.

What do you think about making the docs more clear, that the component will be destroyed and created from scratch? E.g.
> Re-creates the component with new props. This will call ngOnchanges with initial change object.

**Comment by shaman-apprentice** [comment]
Cool :) I'll add this to my personal ToDo's (I'll probably have time to create a PR sometime between next week and the week after). Thanks again for your support and openness

**Comment by timdeschryver** [comment]
No problem, thank you! 
I'm also closing #361
