### ISSUE TITLE
How to test router.navigate calls made by the component under test?

### ISSUE THREAD

**Issue by andreashouben** [testing-library/angular-testing-library#364]
Hi there,

I am having trouble testing a component that calls the navigate function on the router provider.

Example:
```javascript
export class Example implements OnInit {     
  constructor(private readonly router: Router) {}      
  ngOnInit() {       
    router.navigate('/foo/bar')     
  } 
}
```

Usually I would render the Component and Mock the router provider to expect the call of the navigate fn. Unfortunately that seems to interfere with the internal routerTestingmodule.

Ideally the renderResult would return a `location` so that I can simply 
`expect(renderResult.location).toEqual('/foo/bar')`

**Comment by timdeschryver** [comment]
You should still be able to do that @andreashouben , do you have a full example?

**Comment by andreashouben** [comment]
Thanks for your response.

Interesting. I just created a demo project to verify my problem and it just works.

This is the component under test:

```javascript
export class RoutingComponent implements OnInit {
  constructor(private readonly router: Router){    
  }

  ngOnInit(): void {
    this.router.navigate(['/target'])
  }

}
```

and this is the test:

```
describe('RoutingComponent', () => {

  let navigate = jest.fn();
  beforeEach(async () => {
    await render(RoutingComponent, {
      providers: [
        MockProvider(Router, {
            navigate          
        })
      ]
    })
  });

  it('should navigate to target', () =>{
    expect(navigate).toHaveBeenCalledWith(['/target'])
  })
});
```

Which is green. Now I am confused. I did the same in our production code today and I got a strange error message. I will try this with a similar reduced component in production to see if the issue remains there.

**Comment by andreashouben** [comment]
Allright. I was following a false trail. We also import the ActivatedRoute in our component to extract pathparams and we just forgot to provide it.

Sorry for bothering you and thanks for rubberducking :-)
