### ISSUE TITLE
Support IVY compiler and move away from Angular View Engine.

### ISSUE THREAD

**Issue by ultimatekrishna** [testing-library/angular-testing-library#379]
Current Behaviour- View Engine libraries will no longer work with new versions of angular
Expectation- Provide a IVY build.

Ref - NGCC was removed from Angular:
https://github.com/angular/angular/pull/49101

**Comment by timdeschryver** [comment]
Hi @ultimatekrishna thanks for raising this issue.
What part of this library is still using View Engine?

**Comment by ultimatekrishna** [comment]
Closing as we checked again and it has been migrated to IVY.

**Comment by timdeschryver** [comment]
Thanks for the update @ultimatekrishna
