### ISSUE TITLE
Use of throwError makes the next test fail

### ISSUE THREAD

**Issue by zerock54** [testing-library/angular-testing-library#386]
Hello,

I have a component where I am using the RXJS's `throwError` method to re-throw an error from a `catchError` operator.
The test itself passes but the issue is that the error thrown by throwError makes the next test fail.
Here is a reproduction:

```ts
import {Component} from '@angular/core';
import {throwError} from 'rxjs';

@Component({
  selector: 'app-test',
  template: `<button (click)="onTest()">Test</button>`,
  styles: [],
})
export class TestComponent {
  onTest() {
    throwError(() => new Error('myerror')).subscribe();
  }
}
```

```ts
import {render, screen} from '@testing-library/angular';
import userEvent from '@testing-library/user-event';
import {TestComponent} from './test.component';

describe('TestComponent', () => {
  it('does not fail', async () => {
    await render(TestComponent);

    await userEvent.click(screen.getByText('Test'));
  });

  it('fails because of the previous one', async () => {
    await render(TestComponent);

    await userEvent.click(screen.getByText('Test'));
  });
});
```

<img width="500" alt="image" src="https://github.com/testing-library/angular-testing-library/assets/7101750/6b8c1825-46b1-47af-8a1b-76ba9682b1c6">

How can i avoid the error to make the test fail ?
Thanks

**Comment by timdeschryver** [comment]
What are you trying to test here?
Do you expect the throw to happen, or do you just want to prevent the following test from failing?

If it's the latter, you need to wait until all async operations are completed.
For an example see https://github.com/testing-library/angular-testing-library/pull/387
