### ISSUE TITLE
consider using userEvent rather than fireEvent

### ISSUE THREAD

**Issue by markgoho** [testing-library/angular-testing-library#394]
[according to the docs](https://testing-library.com/docs/dom-testing-library/api-events)
> Most projects have a few use cases for fireEvent, but the majority of the time you should probably use [@testing-library/user-event](https://testing-library.com/docs/user-event/intro)

Here's an updated version of `00-single-component.spec.ts`:
``` typescript
import { render, screen } from '@testing-library/angular';
import userEvent from '@testing-library/user-event';

import { SingleComponent } from './00-single-component';

test('renders the current value and can increment and decrement', async () => {
  const user = userEvent.setup()
  await render(SingleComponent);

  const incrementControl = screen.getByRole('button', { name: /increment/i });
  const decrementControl = screen.getByRole('button', { name: /decrement/i });
  const valueControl = screen.getByTestId('value');

  expect(valueControl).toHaveTextContent('0');

  await user.click(incrementControl);
  await user.click(incrementControl);
  expect(valueControl).toHaveTextContent('2');

  await user.click(decrementControl);
  expect(valueControl).toHaveTextContent('1');
});
```

**Comment by sysmat** [comment]
- userEvent  in my case on Chrome Headless 90. not working

**Comment by sysmat** [comment]
- we have CI with different chrome versions and `fireEvent` work for all of them, but `userEvent`  is not

**Comment by timdeschryver** [comment]
Yea, using userEvent is recommended and it would be better to update the examples to use it 😅
Preferably we should also update to the latest user-event version.

Do you want to create a PR for this @markgoho ?

**Comment by markgoho** [comment]
> Yea, using userEvent is recommended and it would be better to update the examples to use it 😅 Preferably we should also update to the latest user-event version.
> 
> Do you want to create a PR for this @markgoho ?

Yes, would love to do this!
