### ISSUE TITLE
Override imports of routed standalone component

### ISSUE THREAD

**Issue by Nosfistis** [testing-library/angular-testing-library#396]
I am having the case of a routed component that requires some resolved data. The component itself has some imports that require stubbing. In the pre-standalone era this was done easily via `imports`. With standalone it should be done via `componentImports`. However, `componentImports` does not override routed component imports, only the rendered component's imports.

```Typescript
await render(MyComponent, {
  componentImports: [FontAwesomeTestingModule],
  declarations: [StubSelectComponent],
  initialRoute: '',
  routes: [
    { path: '', component: MyComponent, resolve: { page: () => requestPageData() } },
  ],
});
```

Now, I know that this is flawed, but I am trying to achieve a truly routed component whose imports are stubbed.

**Comment by timdeschryver** [comment]
Hi, that's an interesting use case.
Could you share a working example (component + test) that isn't using the standalone API?

**Comment by timdeschryver** [comment]
@Nosfistis Yea, I'm looking for a reproduction that can be used to investigate this.

**Comment by timdeschryver** [comment]
@Nosfistis I don't see a way to do this in a generic way that covers many cases.
Instead, I propose a callback in which you can configure the TestBed to your own customized needs #403.
What do you think about it?

**Comment by Nosfistis** [comment]
I think it would work fine, and it would be easy to adopt, since it looks a lot like the angular way currently we can make standalone component mocks:

```Typescript
Testbed.configureTestingModule({
  imports: [MyComponent],
})
  .overrideComponent(MyComponent, {
    add: { imports: [FontAwesomeTestingModule] },
    remove: { imports: [FontAwesomeModule] }
  })
```
