### ISSUE TITLE
How to test drag and drop CdkDragDropModule?

### ISSUE THREAD

**Issue by vmuresanu** [testing-library/angular-testing-library#405]
Hi, I have two dropzones with 3 by 3 items. They are draggable and could be moved between the dropzones.
How can I simulate a drag and drop event so that I test that the initial draggable element from dropzone1 is now in dropzone2? 
I did some research and it would appear that there would be some limitations with JSDom. Nevertheless is there any way to trigger the cdkDrag event with Testing Library?

**Comment by timdeschryver** [comment]
Hi @vmuresanu , I also think this is due to limitations with JSDom.
Because that's the case, we sadly can't provide a solution.
A workaround is to write a test that uses a "real" browser, e.g. using Playwright (or maybe WebDriver.io?).
