### ISSUE TITLE
Add an example for testing @Viewchild

### ISSUE THREAD

**Issue by adanyc** [testing-library/angular-testing-library#414]
I was wondering if you could add an example for testing @Viewchild.
Viewchild is used when you works with custom elements, like components created in stenciljs.

Something like that

`<button (click)="open()">click</button>
<my-modal #modal>Hello</my-modal>

@Viewchild('modal') modal: ElementRef;

open(){
  this.modal.nativeElement.openModal();
}`
How could you test using angular testing library, to capture the modal viewchild

**Comment by timdeschryver** [comment]
What do you want to test?
"Testing" a viewchild should be the same as a child component.
Using screen and the events you can verify/interact with the view child.

**Comment by adanyc** [comment]
> What do you want to test? "Testing" a viewchild should be the same as a child component. Using screen and the events you can verify/interact with the view child.

Thanks you!
