### ISSUE TITLE
Using signal inputs in computed signals is not supposed 

### ISSUE THREAD

**Issue by 003marek** [testing-library/angular-testing-library#454]
In my use case I have a signal input that I later use in a computed signal. In my test I use render function with componentProperties set. After running the tests I see an error inside computed signal that my signal input is not a function. I believe it is caused by the line `delete componentInstance[key]` in `update` function in `testing-libarary.ts` file.

**Comment by timdeschryver** [comment]
Hello @003marek do you have a reproduction?
As an example see #454.
