### ISSUE TITLE
EntryComponents and Ivy

### ISSUE THREAD

**Issue by Fellach** [testing-library/angular-testing-library#66]
Hello,

I have updated Angular to v9.0.1, removed [deprecated](https://angular.io/guide/deprecations#entrycomponents-and-analyze_for_entry_components-no-longer-required) entryComponents properties from containing components which works fine in the browser. The issue pops up during the tests where I'm clicking the button to load a component dynamically. The lib throws the error shown below

```
Error: No component factory found for MyComponent.
Did you add it to @NgModule.entryComponents? 
  at noComponentFactoryError [...]
```

I tried also `"@testing-library/angular": "^9.0.0-beta.1"` but the error still remains. I'm not sure it is a bug, not implemented yet or, most likely, my misconfiguration. Can anyone take a closer look?

PS. Thank you for your outstanding work and bringing this great library into Angular world.

**Comment by timdeschryver** [comment]
Hi @Fellach thanks for creating this issue.
I haven't tested this with `entryComponents`.

**Comment by timdeschryver** [comment]
From what I can see, this isn't something we can fix.
A test written in Jasmine passes, but the same test with Jest fails.

@Fellach is this something you also see?

**Comment by Fellach** [comment]
Hi @timdeschryver thanks for your replies.

Yes, it looks like it is Jest thing not you library. Luckily for me I found the solution, described [here](https://github.com/angular/angular-cli/issues/17110#issuecomment-592349783). All you need is to run a command: `ngcc --properties main` to transform all modules into Ivy versions
