### ISSUE TITLE
[BUG] "export 'render' was not found in '@testing-library/angular'

### ISSUE THREAD

**Issue by geromegrignon** [testing-library/angular-testing-library#87]
## Bug report

On a newly angular 9.1 project, i added testing-library/angular and a counter component as provided into the official [example](https://testing-library.com/docs/angular-testing-library/examples);

When launching `ng test`, i have the following error : 
```
"export 'render' was not found in '@testing-library/angular'
```

## Steps to reproduce 

- `ng new`
- `npm install --dev @testing-library/angular`
- `ng g c counter`
- add content from official example
- run `ng test`

Here is the [repo](https://github.com/geromegrignon/testing-library-issue).

## Dependencies

```json
"dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/forms": "~9.1.0",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "~9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@testing-library/angular": "^9.1.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
```

## Other information

the same error occurs on more complex tests using `fireEvent` or `screen`.

**Comment by timdeschryver** [comment]
Oh shoot! I broke it for the `jasmine/karma` setup 😅
For now, you should be able to use `v9.0.0`.

I will try to get this resolved ASAP.

**Comment by timdeschryver** [comment]
@geromegrignon Can you try again with version 9.1.1 please?
