### ISSUE TITLE
Testing navigation with query params

### ISSUE THREAD

**Issue by skolldev** [testing-library/angular-testing-library#91]
Hi,

Versions:
```
"@angular/router": "~9.1.0",
"@testing-library/angular": "^9.1.0",
"@testing-library/jest-dom": "^5.1.1",
```

I'm trying to test a component that has behaviour based on its query params.
I have my routing configuration:
```js
routes: [
    { path: 'register', component: RegistrationComponent }
]
```

Then, in the test im trying to navigate to it with a query param:
```js
await navigate('register?token=abc');
```
However, I'm getting the following error:
`Cannot match any routes. URL Segment: 'register%3Ftoken%3Dabc'`

Is there a better way to test it? Or am I getting something wrong?

**Comment by timdeschryver** [comment]
Hi @skolldev, could it be that there's a missing base path?
See https://github.com/testing-library/angular-testing-library/blob/master/src/app/examples/09-router.spec.ts#L76-L79 for an example.
I will also try to test it with a query param later today/tomorrow

**Comment by timdeschryver** [comment]
I was able to reproduce it in the example apps, will try to provide a fix for this ASAP. Thanks for creating the issue

**Comment by skolldev** [comment]
Wow Tim, that was super quick! Thanks for your help :)
