### ISSUE TITLE
Pass entrycomponents to the render function

### ISSUE THREAD

**Issue by sjbuysse** [testing-library/angular-testing-library#94]
versions
```
    "@testing-library/angular": "^8.2.0",
    "@testing-library/dom": "^7.1.1",
```

It is not possible at this time to pass an `entrycomponents` array to the `renderOptions` when rendering a component. So it is not possible to test UI components that are dynamically created.

**Comment by timdeschryver** [comment]
Hi, AFAIK this also not possible with the Angular TestBed.
As a work around you can create a module, with the entry component, and import that module in the tests.

**Comment by sjbuysse** [comment]
I guess you're right!
