### ISSUE TITLE
fixture.DebugElement is null

### ISSUE THREAD

**Issue by chadtomkiss-madetech** [testing-library/angular-testing-library#97]
Hey,

When trying to render a component, I am getting:

```
TypeError: Cannot read property 'query' of null
```

This is triggered here:

https://github.com/testing-library/angular-testing-library/blob/89319df8ba8172bb3ff6131534f0cb5b417d1184/projects/testing-library/src/lib/testing-library.ts#L179

Any ideas on why this would be null?

**Comment by timdeschryver** [comment]
Can you share some code, or a reproduction please?

**Comment by chadtomkiss-madetech** [comment]
```
// Component
export class RegistrationComponent implements OnInit {
  @Output() handleRegistration: EventEmitter<any> = new EventEmitter<any>();
  constructor(
    private registrationsService: RegistrationsService,
  ) { }
}

// Test
const handleRegistration = sinon.spy();

const component = await render(RegistrationComponent, {
    imports: [ReactiveFormsModule, HttpClientTestingModule],
    providers: [RegistrationsService],
    componentProperties: {
      handleRegistration: {
        emit: handleRegistration,
      } as any,
    },
});
```

**Comment by chadtomkiss-madetech** [comment]
For some reason there's an `enableProdMode()` in our `app.component.ts` which I think might be what is nulling out `debugElement`.

**Comment by timdeschryver** [comment]
Hmmm, that could be the cause. Have you tried removing it?

**Comment by chadtomkiss-madetech** [comment]
This is exactly the problem 🤦 

Thanks for such a quick reply on the weekend <3
