### ISSUE TITLE
Provide mocks for components or declarations

### ISSUE THREAD

**Issue by bovandersteene** [testing-library/angular-testing-library#98]
Today we have the `provideMock` and `createMock` functionality that we can use for providers.
Is there a thought or a possibility to create something simular for components and declarations.

you can use it like

```typescript
render(TestMyCompnoent, { 
      declarations: [
            provideComponentMock(Component1),
            provideDeclarationMock(Declaration1)
      ], 
      providers: [
        provideMock(MatSnackBar),
        provideMock(PaymentService),
      ],
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
    });
```

Maybe something already exist in the library. If not I can create a PR for it.

**Comment by tonivj5** [comment]
Why not use [ng-mocks](https://github.com/ike18t/ng-mocks#readme)? I think it does that you want.

Sorry, if I have misunderstood you :sweat_smile:

**Comment by timdeschryver** [comment]
I haven't used mocks for components before.
What would be the benefit of using these @bovandersteene ? 
I got the feeling that using the "real" components are components in these tests, but I could be wrong.

Also, wouldn't `NO_ERRORS_SCHEMA` work here?

**Comment by bovandersteene** [comment]
@timdeschryver, indeed most of the time `NO_ERRORS_SCHEMA`will work. But sometimes you want to test if a function is initiated due to the ViewChildren, or something similar

**Comment by timdeschryver** [comment]
If ng-mocks works, I would rather not include extra code to support it in this code base.
We mention ng-mocks somewhere as it might help other devs 🙂
